version: '3'

# Open Platform Model - Development Taskfile
# Main orchestration for opm.dev@v1 module development

# Silent by default - set TASK_VERBOSE=1 or use --verbose to show commands
silent: true

vars:
  MODULE_PATH: opm.dev@v1
  LOCAL_REGISTRY: localhost:5000
  REGISTRY_CONTAINER: opm-registry
  REGISTRY_PORT: 5000
  REGISTRY_DATA_DIR: .registry-data
  CUE_VERSION: v0.15.0

  # Auto-detect CUE cache directory
  CUE_CACHE_DIR:
    sh: |
      if [ -n "$CUE_CACHE_DIR" ]; then
        echo "$CUE_CACHE_DIR"
      elif [ -n "$XDG_CACHE_HOME" ]; then
        echo "$XDG_CACHE_HOME/cue"
      else
        echo "$HOME/.cache/cue"
      fi

dotenv: ['.env']

includes:
  registry-cue:
    taskfile: .tasks/registry-cue.yml
    dir: .

  registry-docker:
    taskfile: .tasks/registry-docker.yml
    dir: .

  cue:
    taskfile: .tasks/cue-common.yml
    dir: .

  publish:
    taskfile: .tasks/publish.yml
    dir: .

tasks:
  # ============================================================================
  # Default task - show help
  # ============================================================================

  default:
    desc: Show available tasks
    cmds:
      - task --list

  # ============================================================================
  # Development Setup
  # ============================================================================

  setup:
    desc: Setup local development environment
    cmds:
      - task: registry-docker:start
      - task: cue:mod:tidy
      - echo "Development environment ready!"
      - echo "Local registry at {{.LOCAL_REGISTRY}}"

  clean:
    desc: Clean all generated files and caches
    cmds:
      - task: cue:clean
      - task: registry-cue:cache:clear
      - echo "Cleaned all artifacts and caches"

  # ============================================================================
  # Quick shortcuts to common tasks
  # ============================================================================

  fmt:
    desc: Format all CUE files
    cmds:
      - task: cue:fmt

  vet:
    desc: Validate all CUE files
    cmds:
      - task: cue:vet

  validate:
    desc: Validate all packages (comprehensive)
    cmds:
      - task: validate:all

  # ============================================================================
  # Registry Management Shortcuts
  # ============================================================================

  registry:start:
    desc: Start Docker OCI registry
    cmds:
      - task: registry-docker:start

  registry:stop:
    desc: Stop Docker OCI registry
    cmds:
      - task: registry-docker:stop

  registry:status:
    desc: Show registry status and modules
    cmds:
      - task: registry-docker:status

  cache:clear:
    desc: Clear CUE module cache
    cmds:
      - task: registry-cue:cache:clear

  cache:path:
    desc: Show CUE cache directory
    cmds:
      - task: registry-cue:cache:path

  # ============================================================================
  # Package-Specific Validation
  # ============================================================================

  units:vet:
    desc: Validate units package
    dir: v1
    cmds:
      - cue vet ./units/...

  traits:vet:
    desc: Validate traits package
    dir: v1
    cmds:
      - cue vet ./traits/...

  blueprints:vet:
    desc: Validate blueprints package
    dir: v1
    cmds:
      - cue vet ./blueprints/...

  policies:vet:
    desc: Validate policies package
    dir: v1
    cmds:
      - cue vet ./policies/...

  core:vet:
    desc: Validate core definitions
    dir: v1
    cmds:
      - cue vet ./core/...

  modules:vet:
    desc: Validate example modules
    dir: v1
    cmds:
      - |
        if find ./modules -name "*.cue" -type f 2>/dev/null | grep -q .; then
          cue vet ./modules/...
        else
          echo "Skipping modules validation (no .cue files found)"
        fi

  examples:vet:
    desc: Validate examples
    dir: v1
    cmds:
      - cue vet ./examples/...

  schemas:vet:
    desc: Validate shared schemas
    dir: v1
    cmds:
      - cue vet ./schemas/...

  # ============================================================================
  # Comprehensive Validation
  # ============================================================================

  validate:all:
    desc: Validate all packages sequentially
    cmds:
      - echo "Validating all packages..."
      - task: core:vet
      - task: units:vet
      - task: traits:vet
      - task: blueprints:vet
      - task: policies:vet
      - task: schemas:vet
      - task: modules:vet
      - task: examples:vet
      - echo "✓ All packages validated successfully"

  validate:parallel:
    desc: Validate all packages in parallel
    deps:
      - core:vet
      - units:vet
      - traits:vet
      - blueprints:vet
      - policies:vet
      - schemas:vet
      - modules:vet
      - examples:vet

  # ============================================================================
  # Watch Mode (auto-format/validate on changes)
  # ============================================================================

  watch:fmt:
    desc: Watch and auto-format CUE files on changes
    watch: true
    sources:
      - "v1/**/*.cue"
    cmds:
      - task: fmt

  watch:vet:
    desc: Watch and auto-validate CUE files on changes
    watch: true
    sources:
      - "v1/**/*.cue"
    cmds:
      - task: vet

  # ============================================================================
  # Information Commands
  # ============================================================================

  info:
    desc: Show module information
    cmds:
      - task: publish:info

  version:
    desc: Show current module version
    cmds:
      - task: publish:version:show

  env:
    desc: Show environment configuration
    cmds:
      - echo "Module Configuration:"
      - echo "  MODULE_PATH={{.MODULE_PATH}}"
      - echo "  LOCAL_REGISTRY={{.LOCAL_REGISTRY}}"
      - echo "  CUE_VERSION={{.CUE_VERSION}}"
      - echo ""
      - echo "Registry:"
      - echo "  CONTAINER={{.REGISTRY_CONTAINER}}"
      - echo "  PORT={{.REGISTRY_PORT}}"
      - echo "  DATA_DIR={{.REGISTRY_DATA_DIR}}"
      - echo ""
      - echo "Cache:"
      - echo "  CUE_CACHE_DIR={{.CUE_CACHE_DIR}}"
