version: '3'

# Template Publishing Tasks
# Each template is a separate CUE module

silent: true

includes:
  config:
    taskfile: ../../.tasks/config.yml
    internal: true

vars:
  # Template OCI paths (without version)
  # Published as: {path}:{version} (e.g., opm.dev/templates/simple:v1.0.0-alpha.1)
  SIMPLE_MODULE: opm.dev/templates/simple
  STANDARD_MODULE: opm.dev/templates/standard
  ADVANCED_MODULE: opm.dev/templates/advanced

tasks:
  # ============================================================================
  # Default task - show help
  # ============================================================================

  default:
    desc: Show available tasks
    cmds:
      - task --list

  # ============================================================================
  # Validation
  # ============================================================================

  validate:simple:
    desc: Validate simple template
    dir: simple
    cmds:
      - echo "Validating simple template..."
      - cue fmt --check ./...
      - cue vet ./...
      - echo "✓ Simple template valid"

  validate:standard:
    desc: Validate standard template
    dir: standard
    cmds:
      - echo "Validating standard template..."
      - cue fmt --check ./...
      - cue vet ./...
      - echo "✓ Standard template valid"

  validate:advanced:
    desc: Validate advanced template
    dir: advanced
    cmds:
      - echo "Validating advanced template..."
      - cue fmt --check ./...
      - cue vet ./...
      - echo "✓ Advanced template valid"

  validate:all:
    desc: Validate all templates
    cmds:
      - task: validate:simple
      - task: validate:standard
      - task: validate:advanced
      - echo ""
      - echo "✓ All templates validated"

  # ============================================================================
  # Publishing - Simple Template
  # ============================================================================

  publish:simple:
    desc: Publish simple template to OCI registry
    summary: |
      Publish the simple template to OCI registry.

      Usage:
        task templates:publish:simple VERSION=v1.0.0-alpha.1
    vars:
      VERSION: '{{.VERSION | default ""}}'
    preconditions:
      - sh: '[ -n "{{.VERSION}}" ]'
        msg: "VERSION required. Usage: task templates:publish:simple VERSION=v1.0.0-alpha.1"
      - sh: echo "{{.VERSION}}" | grep -qE '^v[0-9]+\.[0-9]+\.[0-9]+(-[a-zA-Z0-9.]+)?$'
        msg: "VERSION must follow semver format: v1.0.0-alpha.1"
    dir: simple
    cmds:
      - echo "Publishing {{.SIMPLE_MODULE}} version {{.VERSION}}..."
      - task: validate:simple
      - CUE_REGISTRY={{.LOCAL_REGISTRY}} cue mod publish {{.VERSION}}
      - |
        echo ""
        echo "✓ Published {{.SIMPLE_MODULE}}:{{.VERSION}}"
        echo "  Registry: {{.LOCAL_REGISTRY}}"

  # ============================================================================
  # Publishing - Standard Template
  # ============================================================================

  publish:standard:
    desc: Publish standard template to OCI registry
    summary: |
      Publish the standard template to OCI registry.

      Usage:
        task templates:publish:standard VERSION=v1.0.0-alpha.1
    vars:
      VERSION: '{{.VERSION | default ""}}'
    preconditions:
      - sh: '[ -n "{{.VERSION}}" ]'
        msg: "VERSION required. Usage: task templates:publish:standard VERSION=v1.0.0-alpha.1"
      - sh: echo "{{.VERSION}}" | grep -qE '^v[0-9]+\.[0-9]+\.[0-9]+(-[a-zA-Z0-9.]+)?$'
        msg: "VERSION must follow semver format: v1.0.0-alpha.1"
    dir: standard
    cmds:
      - echo "Publishing {{.STANDARD_MODULE}} version {{.VERSION}}..."
      - task: validate:standard
      - CUE_REGISTRY={{.LOCAL_REGISTRY}} cue mod publish {{.VERSION}}
      - |
        echo ""
        echo "✓ Published {{.STANDARD_MODULE}}:{{.VERSION}}"
        echo "  Registry: {{.LOCAL_REGISTRY}}"

  # ============================================================================
  # Publishing - Advanced Template
  # ============================================================================

  publish:advanced:
    desc: Publish advanced template to OCI registry
    summary: |
      Publish the advanced template to OCI registry.

      Usage:
        task templates:publish:advanced VERSION=v1.0.0-alpha.1
    vars:
      VERSION: '{{.VERSION | default ""}}'
    preconditions:
      - sh: '[ -n "{{.VERSION}}" ]'
        msg: "VERSION required. Usage: task templates:publish:advanced VERSION=v1.0.0-alpha.1"
      - sh: echo "{{.VERSION}}" | grep -qE '^v[0-9]+\.[0-9]+\.[0-9]+(-[a-zA-Z0-9.]+)?$'
        msg: "VERSION must follow semver format: v1.0.0-alpha.1"
    dir: advanced
    cmds:
      - echo "Publishing {{.ADVANCED_MODULE}} version {{.VERSION}}..."
      - task: validate:advanced
      - CUE_REGISTRY={{.LOCAL_REGISTRY}} cue mod publish {{.VERSION}}
      - |
        echo ""
        echo "✓ Published {{.ADVANCED_MODULE}}:{{.VERSION}}"
        echo "  Registry: {{.LOCAL_REGISTRY}}"

  # ============================================================================
  # Publishing - All Templates
  # ============================================================================

  publish:all:
    desc: Publish all templates to OCI registry
    summary: |
      Publish all templates (simple, standard, advanced) to OCI registry.
      All templates will be published with the same version.

      Usage:
        task templates:publish:all VERSION=v1.0.0-alpha.1
    vars:
      VERSION: '{{.VERSION | default "v1.0.0-alpha.1"}}'
    preconditions:
      - sh: '[ -n "{{.VERSION}}" ]'
        msg: "VERSION required. Usage: task templates:publish:all VERSION=v1.0.0-alpha.1"
    cmds:
      - echo "Publishing all templates version {{.VERSION}}..."
      - echo ""

      - task: validate:all
      - echo ""

      - task: publish:simple
        vars:
          VERSION: '{{.VERSION}}'

      - echo ""
      - task: publish:standard
        vars:
          VERSION: '{{.VERSION}}'

      - echo ""
      - task: publish:advanced
        vars:
          VERSION: '{{.VERSION}}'

      - |
        echo ""
        echo "✓ All templates published successfully!"
        echo ""
        echo "Published:"
        echo "  - {{.SIMPLE_MODULE}}:{{.VERSION}}"
        echo "  - {{.STANDARD_MODULE}}:{{.VERSION}}"
        echo "  - {{.ADVANCED_MODULE}}:{{.VERSION}}"
        echo "  Registry: {{.LOCAL_REGISTRY}}"

  # ============================================================================
  # Info and Testing
  # ============================================================================

  info:
    desc: Show template module information
    cmds:
      - |
        echo "Template Modules:"
        echo "================="
        echo ""
        echo "Simple:   {{.SIMPLE_MODULE}}"
        echo "Standard: {{.STANDARD_MODULE}}"
        echo "Advanced: {{.ADVANCED_MODULE}}"
        echo ""
        echo "Registry: {{.LOCAL_REGISTRY}}"

  test:fetch:
    desc: Test fetching templates from OCI registry
    summary: |
      Test that templates can be fetched from the registry.

      Usage:
        task templates:test:fetch VERSION=v1.0.0-alpha.1
    vars:
      VERSION: '{{.VERSION | default ""}}'
    preconditions:
      - sh: '[ -n "{{.VERSION}}" ]'
        msg: "VERSION required"
    cmds:
      - |
        echo "Testing template fetch from {{.LOCAL_REGISTRY}}..."
        echo ""

        TEST_DIR=$(mktemp -d)
        echo "Test directory: $TEST_DIR"
        cd "$TEST_DIR"

        # Initialize test module
        cue mod init test.local/templatetest@v0

        echo "Fetching templates..."
        # Note: cue mod get uses CUE module format with @v1, not OCI :version format
        CUE_REGISTRY={{.LOCAL_REGISTRY}} cue mod get {{.SIMPLE_MODULE}}@v1 || exit 1
        CUE_REGISTRY={{.LOCAL_REGISTRY}} cue mod get {{.STANDARD_MODULE}}@v1 || exit 1
        CUE_REGISTRY={{.LOCAL_REGISTRY}} cue mod get {{.ADVANCED_MODULE}}@v1 || exit 1

        echo ""
        echo "✓ All templates successfully fetched"

        cd - > /dev/null
        rm -rf "$TEST_DIR"

  # ============================================================================
  # Cleanup
  # ============================================================================

  clean:
    desc: Clean generated files from all templates
    cmds:
      - echo "Cleaning template artifacts..."
      - rm -rf simple/cue.mod/gen simple/cue.mod/pkg
      - rm -rf standard/cue.mod/gen standard/cue.mod/pkg
      - rm -rf advanced/cue.mod/gen advanced/cue.mod/pkg
      - echo "✓ Cleaned"
